language: node_js
node_js: 14

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql < backend/test/travis.sql

env:
  PORT=5000
  DB_USER=mulligan_app
  DB_DATABASE=mulligan_development
  DB_PASSWORD=password 
  DB_HOST=localhost
  JWT_SECRET=secret 
  JWT_EXPIRES_IN=608000