module.exports = {
  factionArr: [
    'Neutral',
    'Monster',
    'Nilfgaard',
    'Northern Realms',
    'Scoiatael',
    'Skellige',
    'Syndicate'
  ],
  typeArr: [ null, 'Unit', 'Spell', 'Artifact', 'Leader', 'Strategem' ],
  categoryArr: [
    'Witcher',      'Vampire',        'Human',        'Mage',
    'Dragon',       'Dwarf',          'Elf',          'Relict',
    'Cursed',       'Bandit',         'Beast',        'Spell',
    'Bomb',         'Warfare',        'Druid',        'Organic',
    'Alchemy',      'Warrior',        'Soldier',      'Leader',
    'Agent',        'Knight',         'Ogroid',       'Machine',
    'Siege Engine', 'Wild Hunt',      'Specter',      'Insectoid',
    'Necrophage',   'Crone',          'Construct',    'Demon',
    'Token',        'Dryad',          'Tactic',       'Trap',
    'Ship',         'Raid',           'Pirate',       'Cultist',
    'Aristocrat',   'Plant',          'Nature',       'Support',
    'Gnome',        'Doomed',         'Hazard',       'Location',
    'Treant',       'Blindeyes',      'Witch Hunter', 'Crime',
    'Cutups',       'Halfling',       'Tidecloaks',   'Firesworn',
    'Cleric',       'Crownsplitters', 'Salamandra',   'Mutant',
    'Scenario'
  ],
  keywordArr: [
    'deploy',      'initiative', 'order',         'melee',
    'drain',       'ranged',     'reveal',        'spawn',
    'zeal',        'cooldown',   'adrenaline',    'summon',
    'heal',        'banish',     'vitality',      'doomed',
    'deathwish',   'cataclysm',  'storm',         'veil',
    'frost',       'fog',        'charge',        'rain',
    'Bloodthirst', 'lock',       'formation',     'inspired',
    'bleeding',    'disloyal',   'coin',          'armor',
    'resupply',    'crew',       'barricade',     'exposed',
    'shield',      'purify',     'immune',        'consume',
    'seize',       'thrive',     'dominance',     'bonded',
    'Deploy',      'resilient',  'deathblow',     'ambush',
    'spring',      'Spring',     'discard',       'bloodthirst',
    'berserk',     'conspiracy', 'spying',        'create',
    'poison',      'patience',   'symbiosis',     'harmony',
    'assimilate',  'duel',       'dragons_dream', 'blood_moon',
    'tribute',     'profit',     'fee',           'bounty',
    'intimidate',  'insanity',   'hoard',         'defender',
    'Armor',       'echo',       'devotion',      'veteran',
    'rupture',     'sabbath'
  ],
  rarityArr: [ null, 'Legendary', 'Epic', 'Rare', 'Common' ],
  setArr: [
    'Token',
    'Base',
    'Unmillable',
    'Novigrad',
    'IronJudgement',
    'CrimsonCurse',
    'Thronebreaker',
    'Tutorial',
    'MerchantsOfOfir',
    'MasterMirror',
    'Unreleased1',
    'Unreleased2'
  ]
}
